# 21點基本策略配置檔
# 適用於8副牌，莊家軟17停牌

# 遊戲設定
settings:
  decks: 8
  dealer_stands_soft_17: true
  
# 決策代碼說明
action_codes:
  H: 
    action: "要牌"
    description: "再拿一張牌"
  S: 
    action: "停牌"
    description: "保持現有手牌"
  D: 
    action: "加倍"
    description: "如允許則加倍下注，否則要牌"
  Ds: 
    action: "加倍"
    description: "如允許則加倍下注，否則停牌"
  R: 
    action: "投降"
    description: "如允許則投降，否則要牌"
  Y: 
    action: "分牌"
    description: "分開這對對子"
  N: 
    action: ""
    description: ""  # 不應分牌的對子

# 莊家牌對應索引
dealer_card_index:
  '2': 0
  '3': 1
  '4': 2
  '5': 3
  '6': 4
  '7': 5
  '8': 6
  '9': 7
  '10': 8
  'J': 8
  'Q': 8
  'K': 8
  'A': 9

# 硬牌策略（無A或A算作1點）
hard_strategy:
  # 莊家明牌順序
  dealer_cards: ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A']
  # 玩家手牌點數對應策略
  hands:
    5:  ['H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
    6:  ['H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
    7:  ['H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
    8:  ['H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
    9:  ['H', 'D', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H']
    10: ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'H', 'H']
    11: ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'H']
    12: ['H', 'H', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H']
    13: ['S', 'S', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H']
    14: ['S', 'S', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H']
    15: ['S', 'S', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H']
    16: ['S', 'S', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H']
    17: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']
    18: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']
    19: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']
    20: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']
    21: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']

# 軟牌策略（A算作11點）
soft_strategy:
  # 莊家明牌順序
  dealer_cards: ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A']
  # 玩家手牌點數對應策略（A,2=13, A,3=14, 以此類推）
  hands:
    13: ['H', 'H', 'H', 'D', 'D', 'H', 'H', 'H', 'H', 'H']
    14: ['H', 'H', 'H', 'D', 'D', 'H', 'H', 'H', 'H', 'H']
    15: ['H', 'H', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H']
    16: ['H', 'H', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H']
    17: ['H', 'D', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H']
    18: ['Ds', 'Ds', 'Ds', 'Ds', 'Ds', 'S', 'S', 'H', 'H', 'H']
    19: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']
    20: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']
    21: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S']

# 對子分牌策略
pair_strategy:
  # 莊家明牌順序
  dealer_cards: ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A']
  # 對子對應策略
  pairs:
    'A,A': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N']
    '2,2': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N']
    '3,3': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N']
    '4,4': ['N', 'N', 'N', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N']
    '5,5': ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    '6,6': ['Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N']
    '7,7': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N']
    '8,8': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N']
    '9,9': ['Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N']
    '10,10': ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']

# 投降策略（需要賭場允許投降）
surrender_strategy:
  # 莊家明牌順序
  dealer_cards: ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A']
  # 玩家手牌點數對應策略（Y = 應該投降，N = 不投降）
  hands:
    # 對於 5-13 點，永遠不投降
    5:  ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    6:  ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    7:  ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    8:  ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    9:  ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    10: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    11: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    12: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    13: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    14: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    # 15點對莊家10投降
    15: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N']
    # 16點對莊家9,10,A投降（但不包括對子8,8）
    16: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y']
    # 17點以上永遠不投降
    17: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    18: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    19: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    20: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
    21: ['N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N']